# Generated by Django 5.2.10 on 2026-03-22 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
