# Generated by Django 5.2.10 on 2026-03-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_refreshtoken_token_alter_refreshtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='is_revoked',
        ),
    ]
